### ISSUE TITLE
demo里面编出来的so库是ijk什么版本的？

### ISSUE THREAD

**Issue by gaoyangcr7** [GenialSir/IJKPlayerDemo#1]

**Comment by GenialSir** [comment]
你好，demo里面编译出来so库的ijk版本是0.8.8


| |
张博伦
|
|
***@***.***
|
签名由网易邮箱大师定制
在2022年1月18日 ***@***.***> 写道：

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gaoyangcr7** [comment]
正好用上，多谢！
